// <auto-generated />
namespace ATP2_Final_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserModelCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserModelCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202012171129129_UserModelCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
